version: '3.7'

networks:
  marklogicDHF:

services:
    marklogic.local:
      image: store/marklogicdb/marklogic-server:${ML_VERSION}
      hostname: marklogicDHF.local
      container_name: marklogicDHF.local
      environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=${ADMIN}
        - MARKLOGIC_ADMIN_PASSWORD=${PASSWORD}
        - TZ=Europe/Prague
      ports:
        - 17997-18010:7997-8010
      networks:
        - marklogicDHF


    quickStart:
      build: ./quickStartDockerfile
      depends_on: 
        - 'marklogic'
      hostname: quickstart.local
      container_name: quickstart.local
      environment:
        - quickstart_download_url=${QUICK_START_URL}
      ports:
        - 9080:8080
      networks:
        - marklogicDHF      
      #volumes:
        #- './data-hub-config:/data-hub-config'
        #- './sample-data:/sample-data'
