version: '3.7'

networks:
  marklogicDHF:

services:
    marklogic.dhf.local:
      image: store/marklogicdb/marklogic-server:${ML_VERSION}
      hostname: marklogic.dhf.local
      container_name: marklogic.dhf.local
      environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=${ADMIN}
        - MARKLOGIC_ADMIN_PASSWORD=${PASSWORD}
        - TZ=Europe/Prague
      ports:
        - 17997-18025:7997-8025
      volumes:
        - ./volumes/marklogic.dhf.local/:/var/opt/MarkLogic/
      networks:
        - marklogicDHF


    quick.start.local:
      build: 
        context: .
        dockerfile: quickstart.Dockerfile
        args:
        - quickstart_download_url=${QUICK_START_URL}
      depends_on:     
        - marklogic.dhf.local
      hostname: quick_start.local
      container_name: quick_start.local
      ports:
       - 9080:8080
      networks:
        - marklogicDHF   
      volumes:
       - ./DHF-config:/DHF-config
       - ./data:/data
