version: '3.7'

networks:
  marklogicDHF:

services:
    marklogic.dhf.local:
      image: store/marklogicdb/marklogic-server:${mlVersion}
      hostname: ${stackName}.dhf.local
      container_name: ${stackName}.dhf.local
      environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=${admin}
        - MARKLOGIC_ADMIN_PASSWORD=${password}
        - TZ=Europe/Prague
      ports:
        - ${markLogicPortMapping}:7997-8025
      volumes:
        - ./volumes/${stackName}.dhf.local/:/var/opt/MarkLogic/
      networks:
        - marklogicDHF


    quick.start:
      build: 
        context: .
        dockerfile: quickstart.Dockerfile
        args:
          - quickstart_download_url=${quickStartURL}
      environment:
        - MARKLOGIC_ADMIN_USERNAME=${admin}
        - MARKLOGIC_ADMIN_PASSWORD=${password}
        - stackName=${stackName}
      image: ${stackName}.quick.start
      depends_on:     
        - marklogic.dhf.local
      hostname: ${stackName}.quick_start
      container_name: ${stackName}.quick_start
      ports:
       - ${quickStartPortMapping}:8080
      volumes:
       - ./DHF-config:/DHF-config
       - ./data:/data
      networks:
       - marklogicDHF  

    gradle:
      build: 
        context: .
        dockerfile: gradle.Dockerfile
      depends_on: 
        - quick.start
      volumes:
        - ./DHF-config:/DHF-config
        - ./data:/data
      networks:
        - marklogicDHF



