version: '3.7'

networks:
  marklogicDHF:

services:
    marklogic:
      image: store/marklogicdb/marklogic-server:${ML_VERSION}
      container_name: marklogic.local
      environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=${ADMIN}
        - MARKLOGIC_ADMIN_PASSWORD=${PASSWORD}
        - TZ=Europe/Prague
      ports:
        - 5997-6010:7997-8010
      volumes:
      - ./volumes/marklogic.local/:/var/opt/MarkLogic/
      networks:
      - marklogicDHF